# Generated by Django 3.1 on 2021-09-17 16:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gigs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_Number', models.IntegerField(verbose_name='Card numbers')),
                ('Expiration_date', models.DateField(verbose_name='Expiration dates')),
                ('Name_on_card', models.CharField(max_length=100, verbose_name='Names on Card')),
                ('CVC', models.CharField(blank=True, max_length=100, verbose_name='Nicknames')),
            ],
            options={
                'verbose_name': 'Billinng Information',
                'verbose_name_plural': 'Billing Information',
            },
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certification_name', models.CharField(max_length=30, verbose_name='Certification Names')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
            },
        ),
        migrations.CreateModel(
            name='Business_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Multix_general_account_id', models.CharField(max_length=100, verbose_name='general id')),
                ('Multix_token', models.CharField(max_length=10, verbose_name='Multix ids')),
                ('Name', models.CharField(max_length=100, verbose_name='Names')),
                ('Password', models.CharField(max_length=20, verbose_name='Passwords')),
                ('Contact', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Description', models.CharField(max_length=1000, null=True, verbose_name='Descriptions')),
                ('Place_of_residence', models.CharField(max_length=100)),
                ('Date_of_birth', models.DateField(verbose_name='Dates of birth')),
                ('Profile_pic', models.ImageField(upload_to='')),
                ('Rating', models.IntegerField()),
                ('Date_of_creation', models.DateTimeField(default=datetime.datetime(2021, 9, 17, 9, 16, 46, 395281))),
                ('Preference_1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Preferences')),
                ('Preference_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Preferences')),
                ('Preference_3', models.CharField(blank=True, max_length=30, null=True, verbose_name='Preferences')),
                ('Preference_4', models.CharField(blank=True, max_length=30, null=True, verbose_name='Preferences')),
                ('Billing_Info', models.ManyToManyField(to='Business_Accounts.Billing_Information')),
                ('Certifications', models.ManyToManyField(to='Business_Accounts.Certifications')),
                ('Gigs', models.ManyToManyField(to='Gigs.Gig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Account',
                'verbose_name_plural': 'Business Accounts',
            },
        ),
    ]
