# Generated by Django 3.1 on 2021-09-17 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contract_owner_id', models.CharField(max_length=100)),
                ('Date_started', models.DateField(auto_now_add=True)),
                ('Deadline', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=30, verbose_name='Certification Names')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_gig_id', models.CharField(blank=True, max_length=200, null=True)),
                ('To_gig_id', models.CharField(blank=True, max_length=200, null=True)),
                ('From_account_id', models.CharField(max_length=200)),
                ('To_account_id', models.CharField(max_length=200)),
                ('Date_of_transaction', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='business_account',
            name='Date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 10, 0, 44, 380884)),
        ),
        migrations.AddField(
            model_name='business_account',
            name='Contracts',
            field=models.ManyToManyField(to='Business_Accounts.Contract'),
        ),
        migrations.AddField(
            model_name='business_account',
            name='Languages',
            field=models.ManyToManyField(to='Business_Accounts.Language'),
        ),
        migrations.AddField(
            model_name='business_account',
            name='Notifications',
            field=models.ManyToManyField(to='Business_Accounts.Notification'),
        ),
        migrations.AddField(
            model_name='business_account',
            name='Transactions',
            field=models.ManyToManyField(to='Business_Accounts.Transaction'),
        ),
    ]
