# Generated by Django 3.1 on 2021-09-18 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Accounts', '0003_auto_20210917_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_account',
            name='Contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='business_account',
            name='Date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 11, 22, 16, 40424)),
        ),
    ]
