# Generated by Django 3.1 on 2021-09-18 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Accounts', '0007_auto_20210918_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_account',
            name='Date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 11, 36, 58, 749037)),
        ),
    ]
