# Generated by Django 3.1 on 2021-10-07 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Accounts', '0011_auto_20211003_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_account',
            name='Date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 7, 11, 5, 28, 957458)),
        ),
    ]
