# Generated by Django 3.1 on 2021-10-07 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Accounts', '0012_auto_20211007_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_account',
            name='Date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 7, 11, 23, 23, 454674)),
        ),
    ]
