# Generated by Django 3.1 on 2021-10-11 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Accounts', '0013_auto_20211007_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_account',
            name='Date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 1, 55, 57, 900715)),
        ),
    ]
