# Generated by Django 3.1 on 2021-10-22 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Accounts', '0014_auto_20211011_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reviewer_id', models.CharField(max_length=100)),
                ('Review', models.CharField(max_length=2000)),
                ('Reviewed_gig_id', models.CharField(max_length=100)),
                ('Date_of_review', models.DateTimeField(auto_now_add=True)),
                ('Rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='Gig_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business_account',
            name='Date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 23, 2, 6, 946258)),
        ),
        migrations.AddField(
            model_name='business_account',
            name='Reviews',
            field=models.ManyToManyField(to='Business_Accounts.Review'),
        ),
    ]
