# Generated by Django 3.1 on 2021-10-29 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Accounts', '0016_auto_20211023_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_account',
            name='Date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 13, 28, 47, 930472)),
        ),
    ]
