# Generated by Django 3.1 on 2021-11-03 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Accounts', '0021_auto_20211103_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notify_id',
            new_name='notifier_id',
        ),
        migrations.AlterField(
            model_name='business_account',
            name='Date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 11, 50, 49, 802061)),
        ),
    ]
