# Generated by Django 3.1 on 2021-11-04 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Accounts', '0023_auto_20211103_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='Negotiated_price',
            field=models.CharField(default=10000, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='Type',
            field=models.CharField(default='Selling', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business_account',
            name='Date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 16, 20, 45, 840622)),
        ),
    ]
