# Generated by Django 3.1 on 2021-11-07 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Accounts', '0024_auto_20211104_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_account',
            name='Date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 21, 53, 35, 428076)),
        ),
    ]
