# Generated by Django 3.1 on 2021-11-07 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Accounts', '0025_auto_20211107_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_account',
            name='Date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 0, 46, 38, 884120)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='Date_started',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='Deadline',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
