# Generated by Django 3.1 on 2021-11-08 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Accounts', '0027_auto_20211108_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_account',
            name='Date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 13, 22, 40, 588929)),
        ),
    ]
