# Generated by Django 3.1 on 2021-11-21 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Accounts', '0028_auto_20211108_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Type_id',
            field=models.CharField(default=3, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business_account',
            name='Date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 20, 25, 3, 941001)),
        ),
    ]
