# Generated by Django 3.1 on 2021-12-01 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Accounts', '0030_auto_20211128_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_account',
            name='Date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 23, 0, 4, 530334)),
        ),
    ]
