# Generated by Django 3.1 on 2021-12-03 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Accounts', '0031_auto_20211201_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_account',
            name='Notifications_token',
            field=models.CharField(default='aserrt', max_length=3000, verbose_name='Notifications ids'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business_account',
            name='Date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 14, 57, 37, 855722)),
        ),
    ]
