# Generated by Django 3.1 on 2021-12-04 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Accounts', '0032_auto_20211203_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_account',
            name='Date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 22, 39, 19, 504357)),
        ),
    ]
