# Generated by Django 3.1 on 2021-12-07 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Accounts', '0033_auto_20211204_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_account',
            name='Date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 23, 56, 38, 829551)),
        ),
    ]
