# Generated by Django 3.1 on 2021-09-17 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gig_Additional_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_id', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200, verbose_name='Names')),
                ('File', models.FileField(blank=True, null=True, upload_to='', verbose_name='Files')),
            ],
        ),
        migrations.CreateModel(
            name='Gig_Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('Date_of_application', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Gig_Project_Completed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_id', models.CharField(max_length=200)),
                ('Account_id_of_customer', models.CharField(max_length=200)),
                ('Date_of_application', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Gig_Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_gig_id', models.CharField(max_length=200)),
                ('To_gig_id', models.CharField(max_length=200)),
                ('From_account_id', models.CharField(max_length=200)),
                ('To_account_id', models.CharField(max_length=200)),
                ('Date_of_transaction', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Multix_token', models.CharField(max_length=200)),
                ('Gig_type', models.CharField(max_length=10, verbose_name='Gig Types')),
                ('Gig_name', models.CharField(max_length=100, verbose_name='Gig Names')),
                ('Gig_genre', models.CharField(default='All', max_length=100, verbose_name='Gig genre')),
                ('Gig_description', models.CharField(max_length=1000, verbose_name='Gig Descriptions')),
                ('Gig_date_of_creation', models.DateTimeField(default=datetime.datetime(2021, 9, 17, 9, 16, 46, 187269), verbose_name=' Dates ')),
                ('Gig_days_of_completion', models.IntegerField(blank=True, null=True)),
                ('Gig_deadline', models.DateTimeField(default=datetime.datetime(2021, 9, 17, 9, 16, 46, 187269), verbose_name='Deadlines')),
                ('Gig_expiration_date', models.DateField(blank=True, verbose_name='Gig Expirations')),
                ('Gig_payment_mode', models.CharField(max_length=12, verbose_name='Payment modes')),
                ('Gig_salary', models.IntegerField()),
                ('Gig_location', models.CharField(blank=True, default='Uganda', max_length=100, null=True, verbose_name='Locations')),
                ('Gig_negotiation', models.BooleanField(default=True, verbose_name='Negotiable')),
                ('ShowCase_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('ShowCase_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('ShowCase_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('ShowCase_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('Gig_Applicants', models.ManyToManyField(to='Gigs.Gig_Applicant')),
                ('Gig_Projects', models.ManyToManyField(to='Gigs.Gig_Project_Completed')),
                ('Gig_Transactions', models.ManyToManyField(to='Gigs.Gig_Transaction')),
                ('Gig_info', models.ManyToManyField(to='Gigs.Gig_Additional_info')),
            ],
        ),
    ]
