# Generated by Django 3.1 on 2021-09-17 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gigs', '0002_auto_20210917_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='Gig_date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 14, 27, 16, 689706), verbose_name=' Dates '),
        ),
        migrations.AlterField(
            model_name='gig',
            name='Gig_deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 14, 27, 16, 689706), verbose_name='Deadlines'),
        ),
    ]
