# Generated by Django 3.1 on 2021-09-18 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gigs', '0003_auto_20210917_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='Gig_date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 11, 22, 16, 10424), verbose_name=' Dates '),
        ),
        migrations.AlterField(
            model_name='gig',
            name='Gig_deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 11, 22, 16, 10424), verbose_name='Deadlines'),
        ),
    ]
