# Generated by Django 3.1 on 2021-10-07 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gigs', '0011_auto_20211003_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='Gig_date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 7, 11, 5, 28, 803452), verbose_name=' Dates '),
        ),
        migrations.AlterField(
            model_name='gig',
            name='Gig_deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 7, 11, 5, 28, 803452), null=True, verbose_name='Deadlines'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='Gig_expiration_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 7, 11, 5, 28, 803452), null=True, verbose_name='Gig Expirations'),
        ),
    ]
