# Generated by Django 3.1 on 2021-10-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gigs', '0012_auto_20211007_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='Gig_date_of_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name=' Dates '),
        ),
        migrations.AlterField(
            model_name='gig',
            name='Gig_deadline',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Deadlines'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='Gig_expiration_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Gig Expirations'),
        ),
    ]
