# Generated by Django 3.1 on 2021-10-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gigs', '0013_auto_20211007_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig_Deal_Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_id', models.CharField(max_length=200)),
                ('Bid_amount', models.IntegerField()),
                ('Account_id_of_customer', models.CharField(max_length=200)),
                ('Date_of_application', models.DateField(auto_now_add=True)),
                ('Approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='gig_applicant',
            name='Approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gig_project_completed',
            name='Approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gig_transaction',
            name='Transaction_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gig_applicant',
            name='Date_of_application',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gig_project_completed',
            name='Date_of_application',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='Gig_Deals_Applicants',
            field=models.ManyToManyField(to='Gigs.Gig_Deal_Applicant'),
        ),
    ]
