# Generated by Django 3.1 on 2021-10-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gigs', '0014_auto_20211022_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='Account_id',
            field=models.CharField(default=38, max_length=200),
            preserve_default=False,
        ),
    ]
