# Generated by Django 3.1 on 2021-10-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gigs', '0015_gig_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig_deal_applicant',
            name='Date_of_application',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
