# Generated by Django 3.1 on 2021-11-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gigs', '0017_gig_project_completed_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='Gig_expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gig Expirations'),
        ),
    ]
