# Generated by Django 3.1 on 2021-11-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gigs', '0018_auto_20211103_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig_applicant',
            name='Date_of_application',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gig_project_completed',
            name='Date_of_application',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
