# Generated by Django 3.1 on 2021-11-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gigs', '0019_auto_20211103_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig_applicant',
            old_name='user_id',
            new_name='Account_id_of_customer',
        ),
        migrations.AddField(
            model_name='gig_applicant',
            name='gig_id',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
