# Generated by Django 3.1 on 2021-11-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gigs', '0021_auto_20211107_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig_applicant',
            name='Date_of_application',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gig_deal_applicant',
            name='Date_of_application',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gig_project_completed',
            name='Date_of_application',
            field=models.DateTimeField(),
        ),
    ]
