# Generated by Django 3.1 on 2021-12-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gigs', '0022_auto_20211108_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='Gig_payment_mode',
            field=models.CharField(max_length=300, verbose_name='Payment modes'),
        ),
    ]
