# Generated by Django 3.1 on 2021-12-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gigs', '0023_auto_20211201_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig_applicant',
            name='Approved',
            field=models.CharField(default=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='gig_deal_applicant',
            name='Approved',
            field=models.CharField(default=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='gig_project_completed',
            name='Approved',
            field=models.CharField(default=False, max_length=300),
        ),
    ]
