# Generated by Django 3.2 on 2022-04-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gigs', '0024_auto_20211207_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='ShowCase_1',
            field=models.ImageField(blank=True, null=True, upload_to='ShowCase_1/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='ShowCase_2',
            field=models.ImageField(blank=True, null=True, upload_to='ShowCase_2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='ShowCase_3',
            field=models.ImageField(blank=True, null=True, upload_to='ShowCase_3/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='ShowCase_4',
            field=models.ImageField(blank=True, null=True, upload_to='ShowCase_4/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gig_additional_info',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gig_applicant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gig_deal_applicant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gig_project_completed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gig_transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
